### ISSUE TITLE
"Your Workshop:" is empty

### ISSUE THREAD

**Issue by Marki2019** [Endermanch/koteyka#1]
i opened koteyka and the your workshop thing is empty

**Comment by ThatOneNewUser** [comment]
BECAUSE IT S A MALWARE!! >:(
ur brain: --> .

                /''''''''''''''\
                l 10^10IQ l
my brain: \_______/

**Comment by Marki2019** [comment]
I dont think i am the one with a small brain

**Comment by thisIsP0G11** [comment]
your such a tiny brain!

here's ur brain
.


here's my brain
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l
l'''''''''''''''''''''''''''''''''''''''''''''''l

**Comment by Marki2019** [comment]
what an idiot lmao
